import 'package:comon_orm/comon_orm.dart';
import 'package:comon_orm_postgresql/comon_orm_postgresql.dart';
import 'package:test/test.dart';

void main() {
  group('PostgresqlSchemaApplier', () {
    test(
      'builds table DDL with identity primary key defaults and foreign keys',
      () {
        final schema = const SchemaParser().parse('''
model User {
  id Int @id @default(autoincrement())
  name String
  enabled Boolean @default(false)
  posts Post[]
}

model Post {
  id Int @id @default(autoincrement())
  title String
  payload Json?
  userId Int
  user User @relation(fields: [userId], references: [id])
}
''');

        final statements = const PostgresqlSchemaApplier()
            .createTableStatements(schema);

        expect(statements, hasLength(2));
        expect(
          statements.first,
          contains('GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY'),
        );
        expect(
          statements.first,
          contains('"enabled" BOOLEAN NOT NULL DEFAULT FALSE'),
        );
        expect(statements.last, contains('"payload" JSONB'));
        expect(
          statements.last,
          contains(
            'CONSTRAINT "Post_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id")',
          ),
        );
      },
    );

    test('uses @@map and @map names in generated DDL', () {
      final schema = const SchemaParser().parse('''
model User {
  id Int @id @default(autoincrement()) @map("user_id")
  email String @unique @map("email_address")
  posts Post[]

  @@map("users")
}

model Post {
  id Int @id @default(autoincrement())
  userId Int @map("owner_id")
  user User @relation(fields: [userId], references: [id])

  @@map("posts")
}
''');

      final statements = const PostgresqlSchemaApplier().createTableStatements(
        schema,
      );

      expect(statements.first, contains('CREATE TABLE IF NOT EXISTS "users"'));
      expect(
        statements.first,
        contains(
          '"user_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
        ),
      );
      expect(
        statements.first,
        contains('"email_address" TEXT NOT NULL UNIQUE'),
      );
      expect(statements.last, contains('CREATE TABLE IF NOT EXISTS "posts"'));
      expect(
        statements.last,
        contains(
          'CONSTRAINT "posts_owner_id_fkey" FOREIGN KEY ("owner_id") REFERENCES "users" ("user_id")',
        ),
      );
    });

    test('builds native enum DDL and references enum types in tables', () {
      final schema = const SchemaParser().parse('''
enum TodoStatus {
  pending
  done
}

model Todo {
  id Int @id @default(autoincrement())
  status TodoStatus @default(pending)
}
''');

      final applier = const PostgresqlSchemaApplier();
      final enumStatements = applier.createEnumStatements(schema);
      final tableStatements = applier.createTableStatements(schema);

      expect(enumStatements, hasLength(1));
      expect(
        enumStatements.single,
        contains('CREATE TYPE "TodoStatus" AS ENUM (\'pending\', \'done\')'),
      );
      expect(tableStatements, hasLength(1));
      expect(
        tableStatements.single,
        contains('"status" "TodoStatus" NOT NULL'),
      );
      expect(tableStatements.single, contains('DEFAULT \'pending\''));
    });

    test('uses @@map databaseName as the PostgreSQL type name in enum DDL', () {
      final schema = const SchemaParser().parse('''
enum TodoStatus {
  pending
  done
  @@map("todo_status")
}

model Todo {
  id Int @id @default(autoincrement())
  status TodoStatus
}
''');

      final applier = const PostgresqlSchemaApplier();
      final enumStatements = applier.createEnumStatements(schema);
      final tableStatements = applier.createTableStatements(schema);

      expect(enumStatements, hasLength(1));
      expect(
        enumStatements.single,
        contains("CREATE TYPE \"todo_status\" AS ENUM ('pending', 'done')"),
      );
      expect(tableStatements, hasLength(1));
      expect(
        tableStatements.single,
        contains('"status" "todo_status" NOT NULL'),
      );
    });

    test('maps supported native postgresql field types into DDL', () {
      final schema = const SchemaParser().parse('''
datasource db {
  provider = "postgresql"
  url = env("DATABASE_URL")
}

model User {
  id         Int      @id @default(autoincrement())
  name       String   @db.VarChar(255)
  bio        String?  @db.Text
  payload    Json     @db.JsonB
  metadata   Json?    @db.Json
  blob       Bytes    @db.ByteA
  amount     Decimal  @db.Numeric
  externalId String   @db.Uuid
  createdAt  DateTime @db.Timestamp
  updatedAt  DateTime @db.Timestamptz
}
''');

      final statements = const PostgresqlSchemaApplier().createTableStatements(
        schema,
      );

      expect(statements, hasLength(1));
      expect(statements.single, contains('"name" VARCHAR(255) NOT NULL'));
      expect(statements.single, contains('"bio" TEXT'));
      expect(statements.single, contains('"payload" JSONB NOT NULL'));
      expect(statements.single, contains('"metadata" JSON'));
      expect(statements.single, contains('"blob" BYTEA NOT NULL'));
      expect(statements.single, contains('"amount" NUMERIC NOT NULL'));
      expect(statements.single, contains('"externalId" UUID NOT NULL'));
      expect(statements.single, contains('"createdAt" TIMESTAMP NOT NULL'));
      expect(statements.single, contains('"updatedAt" TIMESTAMPTZ NOT NULL'));
    });

    test('builds composite primary key and unique constraints', () {
      final schema = const SchemaParser().parse('''
model Membership {
  tenantId Int
  slug String
  role String

  @@id([tenantId, slug])
  @@unique([tenantId, role])
}
''');

      final statements = const PostgresqlSchemaApplier().createTableStatements(
        schema,
      );

      expect(statements, hasLength(1));
      expect(statements.single, contains('PRIMARY KEY ("tenantId", "slug")'));
      expect(statements.single, contains('UNIQUE ("tenantId", "role")'));
    });

    test('emits referential actions in foreign key DDL', () {
      final schema = const SchemaParser().parse('''
model User {
  id Int @id @default(autoincrement())
  posts Post[]
}

model Post {
  id Int @id @default(autoincrement())
  userId Int?
  user User? @relation(fields: [userId], references: [id], onDelete: SetNull, onUpdate: Cascade)
}
''');

      final statements = const PostgresqlSchemaApplier().createTableStatements(
        schema,
      );

      expect(
        statements.last,
        contains(
          'CONSTRAINT "Post_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE',
        ),
      );
    });

    test('builds alter statements for foreign key changes', () {
      final schema = const SchemaParser().parse('''
model User {
  id Int @id @default(autoincrement())
  posts Post[]
}

model Post {
  id Int @id @default(autoincrement())
  userId Int?
  user User? @relation(fields: [userId], references: [id], onDelete: Cascade)
}
''');
      final model = schema.findModel('Post')!;
      final field = model.findField('user')!;
      final applier = const PostgresqlSchemaApplier();

      expect(
        applier.dropForeignKeyConstraintStatementForModel(model, field),
        'ALTER TABLE "Post" DROP CONSTRAINT IF EXISTS "Post_userId_fkey"',
      );
      expect(
        applier.addForeignKeyConstraintStatementForModel(
          model,
          field,
          schema: schema,
        ),
        'ALTER TABLE "Post" ADD CONSTRAINT "Post_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE',
      );
    });
  });
}
